#!/usr/bin/env python3
"""Generate `library/prompts/index.yaml` from the prompt files.

The .txt files are the original. The index is derived, so it cannot list a
prompt that does not exist or miss one that does (PUBLICATION P-07).
"""

from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "src"))

import yaml  # noqa: E402

from atlas.core import prompts as prompts_mod  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]


def main() -> int:
    prompts_dir = ROOT / "library" / "prompts"
    index = prompts_mod.build_index(prompts_dir)
    target = prompts_dir / "index.yaml"
    target.write_text(
        "# Generated by scripts/build_library.py. Do not edit by hand.\n"
        + yaml.safe_dump(index, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    print(f"wrote {target.relative_to(ROOT)} — {index['count']} prompts, {len(index['stages'])} stages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
