"""``atlas completion``: shell completion scripts.

Generated from the command tree rather than hand-written, so a new subcommand
is completable the moment it exists. A completion script that lags the tool is
worse than none: it teaches the shell to suggest commands that do not work.
"""

from __future__ import annotations

import argparse
import typing as t

from ...errors import ExitCode

if t.TYPE_CHECKING:  # pragma: no cover
    from .. import Context

SHELLS = ("bash", "zsh", "fish")

GLOBAL_FLAGS = ("-C", "--directory", "--json", "--no-color", "-q", "--quiet",
                "-v", "--verbose", "-h", "--help", "--version")


def register(subparsers: t.Any, add_global_flags: t.Callable[..., None]) -> None:
    parser = subparsers.add_parser(
        "completion",
        help="print a shell completion script",
        description=(
            "Print a completion script for bash, zsh, or fish. Generated from the command tree, "
            "so it never suggests a command the tool does not have."
        ),
        epilog=(
            "atlas completion bash > /etc/bash_completion.d/atlas\n"
            "atlas completion zsh  > ~/.zsh/completions/_atlas\n"
            "atlas completion fish > ~/.config/fish/completions/atlas.fish"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("shell", choices=SHELLS, help="which shell to generate for")
    add_global_flags(parser)
    parser.set_defaults(handler=run)


def _tree() -> tuple[list[tuple[str, str, list[str]]], dict[str, list[str]]]:
    from ..app import command_tree

    tree = command_tree()
    children: dict[str, list[str]] = {}
    for path, _, _ in tree:
        parts = path.split()
        parent = " ".join(parts[:-1])
        children.setdefault(parent, []).append(parts[-1])
    return tree, children


def _bash() -> str:
    tree, children = _tree()
    flags = {path: " ".join(f) for path, _, f in tree}
    top = " ".join(children.get("", []))
    cases = "\n".join(
        f'    "{parent}") echo "{" ".join(subs)}" ;;'
        for parent, subs in sorted(children.items())
        if parent
    )
    flag_cases = "\n".join(
        f'    "{path}") echo "{value}" ;;' for path, value in sorted(flags.items()) if value
    )
    return f"""# atlas bash completion. Generated by `atlas completion bash`.
_atlas_subcommands() {{
  case "$1" in
{cases}
    *) echo "" ;;
  esac
}}
_atlas_flags() {{
  case "$1" in
{flag_cases}
    *) echo "" ;;
  esac
}}
_atlas() {{
  local cur prev words path
  cur="${{COMP_WORDS[COMP_CWORD]}}"
  words=("${{COMP_WORDS[@]:1:COMP_CWORD-1}}")
  path=""
  for w in "${{words[@]}}"; do
    case "$w" in -*) continue ;; esac
    if [ -z "$path" ]; then path="$w"; else path="$path $w"; fi
  done
  if [[ "$cur" == -* ]]; then
    COMPREPLY=($(compgen -W "$(_atlas_flags "$path") {' '.join(GLOBAL_FLAGS)}" -- "$cur"))
    return
  fi
  local subs
  subs="$(_atlas_subcommands "$path")"
  if [ -z "$path" ]; then subs="{top}"; fi
  COMPREPLY=($(compgen -W "$subs" -- "$cur"))
}}
complete -F _atlas atlas
"""


def _zsh() -> str:
    tree, children = _tree()
    summaries = {path: summary.replace("'", "").replace(":", " ") for path, summary, _ in tree}
    blocks = []
    for parent, subs in sorted(children.items()):
        entries = " ".join(
            f"'{s}:{summaries.get((parent + ' ' + s).strip(), '')}'" for s in subs
        )
        key = parent.replace(" ", "_") or "root"
        blocks.append(f"    local -a {key}_cmds\n    {key}_cmds=({entries})")
    body = "\n".join(blocks)
    dispatch = "\n".join(
        f'      "{parent}") _describe "command" {parent.replace(" ", "_")}_cmds ;;'
        for parent in sorted(children)
        if parent
    )
    return f"""#compdef atlas
# atlas zsh completion. Generated by `atlas completion zsh`.
_atlas() {{
{body}
  local path=""
  local -a rest
  rest=(${{words[2,CURRENT-1]}})
  for w in $rest; do
    [[ "$w" == -* ]] && continue
    if [[ -z "$path" ]]; then path="$w"; else path="$path $w"; fi
  done
  case "$path" in
    "") _describe "command" root_cmds ;;
{dispatch}
      *) _files ;;
  esac
}}
compdef _atlas atlas
"""


def _fish() -> str:
    tree, children = _tree()
    lines = ["# atlas fish completion. Generated by `atlas completion fish`.",
             "complete -c atlas -f"]
    for path, summary, flags in tree:
        parts = path.split()
        condition = (
            "__fish_use_subcommand"
            if len(parts) == 1
            else f'__fish_seen_subcommand_from {parts[-2]}'
        )
        escaped = summary.replace("'", "")
        lines.append(f"complete -c atlas -n '{condition}' -a {parts[-1]} -d '{escaped}'")
        for flag in flags:
            lines.append(
                f"complete -c atlas -n '__fish_seen_subcommand_from {parts[-1]}' "
                f"-l {flag.lstrip('-')}"
            )
    for flag in GLOBAL_FLAGS:
        if flag.startswith("--"):
            lines.append(f"complete -c atlas -l {flag.lstrip('-')}")
    return "\n".join(lines) + "\n"


GENERATORS = {"bash": _bash, "zsh": _zsh, "fish": _fish}


def run(ctx: Context) -> ExitCode:
    script = GENERATORS[ctx.args.shell]()
    # Printed bare. This is meant to be redirected into a file.
    print(script, file=ctx.console.stream, end="")
    return ExitCode.OK
